[project]
name = "proyecto-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Programador1", email = "programador1@productoslacteospacos.com" }
]
requires-python = ">=3.14.7"
dependencies = []

[project.scripts]
proyecto-ocr = "proyecto_ocr:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
